server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://todomanagement.cx6gwa8ek7su.eu-north-1.rds.amazonaws.com:3306/todomanagement
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev

app:
  jwt-secret: ef260e9aa3c673af240d17a2660480361a8e081d1ffeca2a5ed0e3219fc18567
  jwt-expiration-milliseconds: 604900000

#
#spring:
#  data:
#    mongodb:
#      uri: mongodb+srv://dev:dev1234567890@cluster0.zddpw.mongodb.net/mydatabase?retryWrites=true&w=majority&appName=Cluster0
#      database: mydatabase
#      auto-index-creation: true
#server:
#  port: 8080  # Or any port you prefer
